### ISSUE TITLE
 Failed to detect supported framework

### ISSUE THREAD

**Issue by SyCode7** [cloud66-oss/starter#69]
I have tried to use  `starter`  on windows. I always have the error ` Failed to detect supported framework`
What could be the cause, I installed bu downloading from the link provided. Same error  when executing starter on Ubuntu 14:

`root@test-virtual-machine:/home# ./starter_linux_amd64 -p -g dockerfile /codegen/python_client
Starter (c) 2017 Cloud66 Inc.
 Checking templates in /home/test/.starter
 ----> Downloading from https://raw.githubusercontent.com/cloud66/starter/master/templates/templates.json
 No local templates found. Downloading now.
 ----> Downloading from https://raw.githubusercontent.com/cloud66/starter/master/templates/templates.json
 ----> Downloading from https://raw.githubusercontent.com/cloud66/starter/master/templates/node.dockerfile.template
 ----> Downloading from https://raw.githubusercontent.com/cloud66/starter/master/templates/python.dockerfile.template
 ----> Downloading from https://raw.githubusercontent.com/cloud66/starter/master/templates/ruby.dockerfile.template
 ----> Downloading from https://raw.githubusercontent.com/cloud66/starter/master/templates/php.dockerfile.template
 ----> Downloading from https://raw.githubusercontent.com/cloud66/starter/master/templates/service.yml.template
 ----> Downloading from https://raw.githubusercontent.com/cloud66/starter/master/templates/docker-compose.yml.template
 Local templates are up to date
 Detecting framework for the project at -g
 Failed to detect supported framework
`

**Comment by khash** [comment]
May I ask what is the framework you are expecting Starter to detect? Is it possible to share the code it needs to analyse?

**Comment by SyCode7** [comment]
Hi @khash I am trying to analyse the sample pet-store application provided here : [https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore](url)

**Comment by khash** [comment]
@SyCode7 the link is to the page for many different languages. Which one are you trying?

**Comment by SyCode7** [comment]
@khash it fails to detect the go-server  i generated in y local pc. Here is the output 
`root@slingshot:/home/test/git/risk-assess/spring_petclinic_customers_go# starter -g dockerfile
 Starter (c) 2017 Cloud66 Inc.
 Checking templates in /root/.starter
 ----> Downloading from https://raw.githubusercontent.com/cloud66/starter/master/templates/templates.json
 Local templates are up to date
 Detecting framework for the project at /home/test/git/risk-assess/spring_petclinic_customers_go
 Failed to detect supported framework
`

**Comment by khash** [comment]
Starter supports Rails (Rack) and Node frameworks, PHP and Python. Goland is not one of those yet!
