### ISSUE TITLE
Support for java and .net framework

### ISSUE THREAD

**Issue by yoge28** [cloud66-oss/starter#72]
Hi,

could you please add these frameworks too for java and .net?

Regards,
Yogesh

**Comment by khash** [comment]
Hi @yoge28 thank you for the feedback. We don't have support for .net on the roadmap yet but Java certainly is possible to add. Which frameworks on Java are you using?

**Comment by yoge28** [comment]
Hi @khash,

I am using java 1.8.0_60 framework.
